#!/bin/bash

PLAN_FILE=$1
OPA_RULES_DIR=$2
JSON_FILE=plan.json

# check number of args
if [[ $# -ne 2 ]]; then
	echo "Usage: $0 <terraform_plan> <opa_rules_path>"
	echo ""
	echo "  terraform_plan: terraform plan file generated by 'terraform plan'"
	echo "  opa_rules_path: folder with OPA rules for terraform"
	echo ""
	echo "  $0 plan.tfplan /path/to/terraform/opa/rules"
	exit 1
fi

# check if file exists
if [ ! -f "$PLAN_FILE" ]; then
	exit 1
fi

# convert tf plan to json
terraform show -no-color -json $PLAN_FILE > $JSON_FILE
RET=$?
if [ $RET -eq 0 ]; then
	conftest test $JSON_FILE -p $OPA_RULES_DIR
	RETCODE=$?
fi

exit $RETCODE
